languageCode = "en-us"
title = "Fluvio"

enableRobotsTXT = true
pygmentsUseClasses = true
enableEmoji = true

disableKinds = ["taxonomyTerm"]

staticDir = ["static", "code"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe = true

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"  

[params]
  version = "2.0.0"
  description = "Real-time Data Streaming Platform"
  company_url = "https://www.infinyon.com"
  fluvio_cloud= "https://cloud.fluvio.io/signup"
  company_logo = "/images/assets/infinyon-logo-text.svg"
  company_logo_white = "/images/assets/infinyon-logo-text-white.svg"
  site_logo = "/images/assets/fluvio-with-text.svg"

[menu]
  [[menu.fluvio]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"
    weight = 100

  [[menu.fluvio]]
    identifier = "connectors"
    name = "Connectors"
    url = "/connectors/"
    weight = 101

  [[menu.fluvio]]
    identifier = "smartmodules"
    name = "SmartModules"
    url = "/smartmodules/"
    weight = 102

  [[menu.fluvio]]
    identifier = "cli"
    name = "CLI"
    url = "/cli/"
    weight = 103

  [[menu.fluvio]]
    identifier = "api"
    name = "APIs"
    url = "/api/"
    weight = 104

  [[menu.fluvio]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = 105

  [[menu.fluvio]]
    identifier = "chat"
    url = "https://discordapp.com/invite/bBG2dTz"
    pre = "fab fa-discord"
    weight = 160

  [[menu.infinyon]]
    identifier = "blog"
    name = "Blog"
    url = "https://www.infinyon.com/blog"
    pre = "fab fa-blogger"
    weight = 100
  
  [[menu.infinyon]]
    identifier = "webinars"
    name = "Webinars"
    url = "https://www.infinyon.com/webinars"
    pre = "fas fa-desktop"
    weight = 110

  [[menu.infinyon]]
    identifier = "use-cases"
    name = "Use Cases"
    url = "https://www.infinyon.com/use-cases"
    pre = "fas fa-tools"
    weight = 120