[build]
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.68.3"

[[redirects]]
  from = "/blog/2021/01/websocket-glue-for-streaming-apps/"
  to = "https://www.infinyon.com/blog/2021/01/websocket-glue-for-streaming-apps/"
  status = 301
  force = true 

[[redirects]]
  from = "/blog/2021/02/bot-assistant/"
  to = "https://www.infinyon.com/blog/2021/02/bot-assistant/"
  status = 301
  force = true 

[[redirects]]
  from = "/blog/2021/03/announcing-fluvio-cloud-platform/"
  to = "https://www.infinyon.com/blog/2021/03/announcing-fluvio-cloud-platform/"
  status = 301
  force = true 

[[redirects]]
  from = "/blog/2021/03/python-client/"
  to = "https://www.infinyon.com/blog/2021/03/python-client/"
  status = 301
  force = true 

[[redirects]]
  from = "/blog/2021/03/key-value-records/"
  to = "https://www.infinyon.com/blog/2021/03/key-value-records/"
  status = 301
  force = true 

[[redirects]]
  from = "/blog/2021/04/node-bindgen-tuples/"
  to = "https://www.infinyon.com/blog/2021/04/node-bindgen-tuples/"
  status = 301
  force = true 

[[redirects]]
  from = "/blog/2021/04/github-actions-best-practices/"
  to = "https://www.infinyon.com/blog/2021/04/github-actions-best-practices/"
  status = 301
  force = true 

[[redirects]]
  from = "/blog/2021/04/rust-custom-test-harness/"
  to = "https://www.infinyon.com/blog/2021/04/rust-custom-test-harness/"
  status = 301
  force = true 

[[redirects]]
  from = "/blog/2021/05/java-client/"
  to = "https://www.infinyon.com/blog/2021/05/java-client/"
  status = 301
  force = true 

[[redirects]]
  from = "/blog/2021/05/bors-confident-merges/"
  to = "https://www.infinyon.com/blog/2021/05/bors-confident-merges/"
  status = 301
  force = true 

[[redirects]]
  from = "/blog/"
  to = "https://www.infinyon.com/blog/"
  status = 301
  force = true 